---
abstract: 'Setup symlink (existence, target)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Slurp: 0
  File::chdir: 0
  Module::Build: 0.3601
  Test::More: 0.96
  Test::Setup: 1.01
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Setup-File-Symlink
requires:
  Data::Dump::Partial: 0
  File::Copy::Recursive: 0
  File::Path: 2.08
  Log::Any: 0
  Perinci::Sub::Gen::Undoable: 0.08
  Rinci: v1.1.18
  Setup: v1.0.0
  UUID::Random: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Setup-File-Symlink/
  repository: http://github.com/sharyanto/perl-Setup-File-Symlink
version: 0.20
